name: pyBEF
channels:
  - pyviz
  - conda-forge
  - defaults
dependencies:
  - bokeh=1.1.0
  - cftime=1.0.3.4
  - fiona=1.8.6
  - gdal=2.4.1
  - geopandas=0.5.0
  - holoviews=1.12.2
  - hvplot=0.4.0
  - netcdf4=1.5.1.2
  - numpy=1.16.3
  - panel=0.5.1
  - proj4=6.0.0
  - requests=2.21.0
  - shapely=1.6.4
  - xarray=0.12.1